export const elements = {
  startScreen: document.querySelector("#start-screen"),
  quizScreen: document.querySelector("#quiz-screen"),
  resultScreen: document.querySelector("#result-screen"),
  topicButtons: document.querySelectorAll(".topic-button"),
  categorySelect: document.querySelector("#category-select"),
  modeSelect: document.querySelector("#mode-select"),
  amountSelect: document.querySelector("#amount-select"),
  startButton: document.querySelector("#start-button"),
  checkButton: document.querySelector("#check-button"),
  nextButton: document.querySelector("#next-button"),
  quitButton: document.querySelector("#quit-button"),
  restartButton: document.querySelector("#restart-button"),
  score: document.querySelector("#score"),
  progress: document.querySelector("#progress"),
  progressBar: document.querySelector("#progress-bar"),
  categoryLabel: document.querySelector("#category-label"),
  questionType: document.querySelector("#question-type"),
  question: document.querySelector("#question"),
  answerArea: document.querySelector("#answer-area"),
  feedback: document.querySelector("#feedback"),
  resultText: document.querySelector("#result-text")
};
